import { StyleSheet } from 'react-native';
import { Fonts } from '../constants/Fonts';

export const widgetStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mainScrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
    paddingTop: 85,
    paddingHorizontal: 30,
  },
  daySection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dayText: {
    fontSize: 60,
    fontWeight: '700',
    fontFamily: Fonts.header,
    lineHeight: 64,
  },
  redDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dateSection: {
    alignItems: 'flex-end',
  },
  dateText: {
    fontSize: 18,
    fontWeight: '400',
    fontFamily: Fonts.body,
    lineHeight: 22,
  },
  yearText: {
    fontSize: 18,
    fontWeight: '400',
    fontFamily: Fonts.body,
    lineHeight: 22,
  },
  themeToggle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  themeIcon: {
    fontSize: 18,
  },
  summarySection: {
    marginBottom: 20,
    paddingHorizontal: 25,
  },
  greetingText: {
    fontSize: 40,
    fontWeight: '600',
    fontFamily: Fonts.header,
    marginBottom: 8,
  },
  summaryText: {
    fontSize: 28,
    fontWeight: '500',
    fontFamily: Fonts.body,
    lineHeight: 34,
  },
  highlightText: {
    fontWeight: '700',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
    paddingHorizontal: 12,
  },
  statItem: {
    fontSize: 14,
    fontFamily: Fonts.body,
  },
  statNumber: {
    fontWeight: '600',
  },
  widgetContainer: {
    flex: 1,
    position: 'relative',
    minHeight: 800,
    marginTop: 12,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '600',
    fontFamily: Fonts.header,
    lineHeight: 18,
  },
  widgetArrow: {
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrowIcon: {
    fontSize: 12,
    fontWeight: '400',
  },
  eventsContent: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  nextEventRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  eventTime: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginRight: 10,
  },
  eventTimeText: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Fonts.body,
    lineHeight: 20,
  },
  eventPeriod: {
    fontSize: 11,
    fontWeight: '400',
    fontFamily: Fonts.body,
    marginLeft: 3,
    opacity: 0.6,
  },
  eventDetails: {
    flex: 1,
  },
  eventTitle: {
    fontSize: 13,
    fontWeight: '600',
    fontFamily: Fonts.body,
    marginBottom: 2,
    lineHeight: 16,
  },
  eventDate: {
    fontSize: 11,
    fontWeight: '400',
    fontFamily: Fonts.body,
    opacity: 0.6,
  },
  nextEventInfo: {
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.06)',
    marginTop: 4,
  },
  nextLabel: {
    fontSize: 10,
    fontWeight: '500',
    fontFamily: Fonts.body,
    opacity: 0.6,
  },
  habitsContent: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  habitRingContainer: {
    marginBottom: 6,
  },
  habitRingBackground: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  habitRingProgress: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 3,
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
    transform: [{ rotate: '-45deg' }],
  },
  habitPercentageContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 3,
  },
  habitPercentage: {
    fontSize: 15,
    fontWeight: '700',
    fontFamily: Fonts.header,
  },
  habitPercentageSymbol: {
    fontSize: 10,
    fontWeight: '600',
    fontFamily: Fonts.header,
  },
  habitName: {
    fontSize: 11,
    fontWeight: '500',
    fontFamily: Fonts.body,
    opacity: 0.7,
    textAlign: 'center',
  },
  bigNumber: {
    fontSize: 22,
    fontWeight: '700',
    fontFamily: Fonts.header,
    lineHeight: 26,
  },
  subText: {
    fontSize: 11,
    fontWeight: '400',
    fontFamily: Fonts.body,
    opacity: 0.6,
  },
  bottomText: {
    fontSize: 10,
    fontWeight: '400',
    fontFamily: Fonts.body,
    opacity: 0.5,
  },
  askMinaraSmallContent: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    flex: 1,
    alignItems: 'flex-start',
  },
  askMinaraMainSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  askMinaraMainIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  askMinaraLargeIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  askMinaraLargeIconText: {
    fontSize: 12,
    fontWeight: '700',
    fontFamily: Fonts.header,
  },
  askMinaraTextBubble: {
    flex: 1,
  },
  askMinaraText: {
    fontSize: 13,
    fontWeight: '500',
    fontFamily: Fonts.body,
    lineHeight: 16,
  },
  askMinaraBottomIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  askBottomButton: {
    width: 16,
    height: 16,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  askBottomIcon: {
    fontSize: 10,
    fontWeight: '600',
    fontFamily: Fonts.header,
  },
  prayersProgressGrid: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  prayerMainContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  prayerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  prayerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 6,
  },
  prayerDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    marginRight: 3,
  },
  prayerName: {
    fontSize: 9,
    fontWeight: '500',
    fontFamily: Fonts.body,
  },
  progressText: {
    fontSize: 11,
    fontWeight: '600',
    fontFamily: Fonts.header,
    textAlign: 'center',
  },
  journalContent: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  journalPromptSection: {
    marginBottom: 8,
  },
  journalDayLabel: {
    fontSize: 9,
    fontWeight: '600',
    fontFamily: Fonts.header,
    marginBottom: 3,
    opacity: 0.6,
    textTransform: 'uppercase',
  },
  journalPrompt: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: Fonts.body,
    lineHeight: 16,
  },
  journalMetaSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  journalIconsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  journalIcon: {
    width: 16,
    height: 16,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  journalIconText: {
    fontSize: 10,
  },
  cohortContent: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  cohortMainSection: {
    marginBottom: 8,
  },
  cohortCard: {
    width: '100%',
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  cohortCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cohortMainText: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: Fonts.header,
  },
  cohortSubText: {
    fontSize: 11,
    fontWeight: '500',
    fontFamily: Fonts.body,
    opacity: 0.7,
  },
  cohortFooter: {
    alignItems: 'center',
  },
  cohortAppName: {
    fontSize: 10,
    fontWeight: '500',
    fontFamily: Fonts.body,
    opacity: 0.6,
  },
  testButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 16,
    alignItems: 'center',
    marginHorizontal: 30,
  },
  testButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Fonts.header,
  },
}); 